baseURL = "https://davidsichinava.github.io/pollster.ge"
languageCode = "en-US"
title = "Pollster.ge"
# theme = "aether"
# theme = "twentyfourteen"
# theme = "techdoc"
# theme = "hugo-flex"
# theme = "minimal-bootstrap-hugo-theme"
theme = "anubis"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "This is the blog section"
    title = "blog section"
    url = "/about/"
    weight = -110

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "Pollster.ge"
    contentDir = "content/english"
    languageName = "English"
    weight = 1
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 2

  [languages.ka]
    title = "Pollster.ge"
    contentDir = "content/kartuli"
    languageName = "ქართული"
    weight = 2
[[menu.main]]
  identifier = "about"
  name = "ჩვენს შესახებ"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "posts"
  name = "პოსტები"
  url = "/posts/"
  weight = 2


defaultContentLanguageInSubdir = true

canonifyURLs =  true

sectionPagesMenu = "main"