baseURL = "https://davidsichinava.github.io/pollster.ge"
# languageCode = "en-US"
defaultContentLanguageInSubdir = false
DefaultContentLanguage = "en"
title = "Pollster.ge"
theme = "anubis"

[languages]
  [languages.en]
    title = "Pollster.ge"
    contentDir = "content/english"
    languageName = "English"
    weight = 1

[[languages.en.menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[languages.en.menu.main]]
  identifier = "methods"
  name = "Methodology"
  url = "/Methods/"
  weight = 2

[languages.ka]
    title = "Pollster.ge"
    contentDir = "content/kartuli"
    languageName = "ქართული"
    weight = 2
	
[[languages.ka.menu.main]]
  identifier = "about"
  name = "ჩვენს შესახებ"
  url = "../ka/about/"
  weight = 1

[[languages.ka.menu.main]]
  identifier = "methods"
  name = "მეთოდოლოგია"
  url = "../ka/methods/"
  weight = 2

[taxonomies]
category = "categories"
tag = "tags"
