baseURL = "https://davidsichinava.github.io/pollster.ge"
languageCode = "en-US"
title = "Pollster.ge"
# theme = "aether"
# theme = "twentyfourteen"
theme = "techdoc"
# theme = "hugo-flex"
# theme = "minimal-bootstrap-hugo-theme"


DefaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "Pollster.ge"
    contentDir = "content/english"
    languageName = "English"
    weight = 1
	[[languages.en.menu.main]]
	url    = "/"
	name   = "Home"
	weight = 0
	[[languages.en.menu.main]]
	url    = "/methods"
	name   = "Methodology"
	weight = 0

  [languages.ka]
    title = "Pollster.ge"
    contentDir = "content/kartuli"
    languageName = "ქართული"
    weight = 2
	[[languages.ka.menu.main]]
	url    = "/"
	name   = "თავფურცელი"
	weight = 0
	[[languages.ka.menu.main]]
	url    = "/methods"
	name   = "მეთოდოლოგია"
	weight = 0

defaultContentLanguageInSubdir = true

