baseURL = "https://davidsichinava.github.io/pollster.ge"
languageCode = "en-US"
title = "Pollster.ge"
# theme = "aether"
# theme = "twentyfourteen"
# theme = "techdoc"
# theme = "hugo-flex"
# theme = "minimal-bootstrap-hugo-theme"
theme = "anubis"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "This is the blog section"
    title = "blog section"
    url = "/about/"
    weight = 1

DefaultContentLanguage = "ka"
[languages]
  [languages.en]
    title = "Pollster.ge"
    contentDir = "content/english"
    languageName = "English"
    weight = 1
[[languages.en.menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[languages.en.menu.main]]
  identifier = "methods"
  name = "Methodology"
  url = "/Methods/"
  weight = 2

[languages.ka]
    title = "Pollster.ge"
    contentDir = "content/kartuli"
    languageName = "ქართული"
    weight = 2
	
[[languages.ka.menu.main]]
  identifier = "about"
  name = "ჩვენს შესახებ"
  url = "/about/"
  weight = 1

[[languages.ka.menu.main]]
  identifier = "methods"
  name = "მეთოდოლოგია"
  url = "/methods/"
  weight = 2


defaultContentLanguageInSubdir = true

[taxonomies]
category = "categories"
tag = "tags"
