baseURL = "https://pollsterge.github.io"
# languageCode = "en-US"
defaultContentLanguageInSubdir = false
DefaultContentLanguage = "en"
canonifyURLs = "true"
title = "Pollster.ge"
theme = "anubis"

[languages]
  [languages.en]
    title = "Pollster.ge"
    contentDir = "content/english"
    languageName = "English"
    weight = 1

[[languages.en.menu.main]]
  identifier = "about"
  name = "About"
  url = "../en/about/"
  weight = 1

[[languages.en.menu.main]]
  identifier = "methods"
  name = "Methodology"
  url = "../en/methods/"
  weight = 2

[[languages.en.menu.main]]
  identifier = "maps"
  name = "Map"
  url = "../en/maps_18/"
  weight = 3
 
[languages.ka]
    title = "Pollster.ge"
    contentDir = "content/kartuli"
    languageName = "ქართული"
    weight = 2
	
[[languages.ka.menu.main]]
  identifier = "about"
  name = "ჩვენს შესახებ"
  url = "../ka/about/"
  weight = 1

[[languages.ka.menu.main]]
  identifier = "methods"
  name = "მეთოდოლოგია"
  url = "../ka/methods/"
  weight = 2
  
[[languages.ka.menu.main]]
  identifier = "maps"
  name = "რუკა"
  url = "../ka/maps_18/"
  weight = 3

[params]
    customCss = ["css/pollster.css"]